schema_version = "1.0.0"

id = "dt_deantools_main"
version = "1.0.0"
name = "DeanTools"
tagline = "Main hub for all DT add-ons"
maintainer = "Dean Zarkov <deanzarkov@protonmail.com>"
type = "add-on"

tags = ["User Interface"]

blender_version_min = "5.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]